export const characters = {
  tighnari: {
    name: 'Tighnari',
    path: '/tighnari.jpg',
    moneybuff: 1.05,
    expbuff: 1.05,
    desc: 'protector of nature, this boy gal is delighted to join you',
    rarity: 'common',
  },
  yuu: {
    name: 'Yuu',
    path: '/yuu.jpg',
    moneybuff: 1.2,
    expbuff: 1,
    desc: "looking to know what 'true love' feels like, maybe you can help?",
    rarity: 'common',
  },
  mei: {
    name: 'Mei',
    path: '/mei.jpg',
    moneybuff: 1,
    expbuff: 1.2,
    desc: 'the smart and elegant student council president',
    rarity: 'common',
  },
  aya: {
    name: 'Aya',
    path: '/aya.jpg',
    moneybuff: 0.5,
    expbuff: 2,
    desc: 'bubbly girl with an avid obsession of 90s rock',
    rarity: 'common',
  },
  koga: {
    name: 'Koga',
    path: '/koga.jpg',
    moneybuff: 0.5,
    expbuff: 2,
    desc: 'shy girl with an avid obsession of 90s rock',
    rarity: 'rare',
  },
  iroha: {
    name: 'Iroha',
    path: '/iroha.jpg',
    moneybuff: 0.5,
    expbuff: 2,
    desc: 'overworked high school student, likes gaming and watching her idol sing',
    rarity: 'rare',
  },
  kaguya: {
    name: 'Kaguya',
    path: '/kaguya.jpg',
    moneybuff: 0.5,
    expbuff: 2,
    desc: 'from space, is 3000 years old',
    rarity: 'rare',
  },
  touko: {
    name: 'Touko',
    path: '/touko.jpg',
    moneybuff: 0.5,
    expbuff: 2,
    desc: 'student council president, loves to not be loved',
    rarity: 'legendary',
  },
  vivian: {
    name: 'Vivian',
    path: '/vivian.jpg',
    moneybuff: 0.5,
    expbuff: 2,
    desc: 'genshin impact',
    rarity: 'legendary',
  },
};
